### ISSUE TITLE
Installation fails on latest ubuntu 18.04.1 fresh iinstall with chimera 1.13 latest stable build

### ISSUE THREAD

**Issue by pratik-narain** [insilichem/tangram#4] opened 2018-09-22 04:34 UTC
This is the error message I receive.

`installing: Tangram Suite extensions with pip ...
Traceback (most recent call last):
  File "/home/pratik/tangram/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
ERROR: executing post_install.sh failed
`
This always happens after the rdkit installation step. Please provide some help or documentation.

**Comment by jaimergp** [comment] 2018-09-22 11:14
Hi, this seems to do with a mix between system's `pip` and Tangram's. I'll try to reproduce your problem with a VM, but in the meantime you can try some of the solutions proposed in this other thread:

https://github.com/pypa/pip/issues/5253

**Comment by pratik-narain** [comment] 2018-09-22 14:30
Hello. I have tried the solutions mentioned in the above thread to no avail. My system does not have pip installed so the only pip present is in the tangram executable. I wonder if there is a way to decompress the .sh file and manually change this import line as suggested in the above thread.

**Comment by jaimergp** [comment] 2018-09-26 10:35
Hi again! Then, my gut is telling me that this could be solved by creating an updated installer for Tangram. I am currently installing the Ubuntu VM and will report back as soon as I have something functional.

**Comment by pratik-narain** [comment] 2018-09-26 11:07
Thank you very much. I am working in a lab where we don't do much in silico
work but based on the docs I would very much like to introduce the Tangram
suite for our structural analysis.

**Comment by jaimergp** [comment] 2018-09-26 11:31
Hi!

Unfortunately, I cannot reproduce that error and got Tangram to install OK in my VM. These are the steps I followed, in case you want to try:

1. Downloaded Ubuntu 18.04.1 Desktop and installed it in a new VirtualBox 10GB HDD 4GB RAM Virtual Machine.
2. Downloaded and installed UCSF Chimera 1.13: `cd Downloads; chmod +x chimera* && ./chimera*`. All options set to default.
3. Softlinked chimera binary to `~/.local/bin`, nonexisting by default so: `mkdir -p ~/.local/bin && ln -s ~/.local/UCSF-Chimera-1.13/bin/chimera ~/.local/bin/chimera`.
4. Added `~/.local/bin` to `$PATH`: `echo 'export PATH="~/.local/bin:$PATH"' >> ~/.bashrc`. Reopen terminal.
5. Installed `git` and `cython` (for Prody installation): `sudo apt install git cython`.
6. Downloaded and installed Tangram 0.0.6 for Linux: `bash tangram*.sh`.
7. Followed the instructions at the end of the installer to setup the `tangram` launcher.

A few warnings might appear, but it is OK (openbabel is not included by default and `PLIP` complains, but that's normal).

**Comment by pratik-narain** [comment] 2018-09-26 12:33
I'll try these tonight and get back to you.

**Comment by pratik-narain** [comment] 2018-09-26 13:44
Hello. I tried as you suggested on a fresh install of ubuntu. I am still getting the same error.
`installing:` boost-1.56.0-py27_3 ...
installing: rdkit-2016.03.4-np111py27_1 ...
installing: Tangram Suite extensions with pip ...
Traceback (most recent call last):
  File "/home/pratik/tangram/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
ERROR: executing post_install.sh `failed`
I'll keep looking for a solution. Thank you.

**Comment by jaimergp** [comment] 2018-09-26 13:49
Can you run `echo $PATH` in your terminal and report the results? Also, for completeness, report the output of `env | sort`.

**Comment by pratik-narain** [comment] 2018-09-27 14:04
PATH

`/home/pratik/tcoffee/Version_11.00.8cbe486/bin:/home/pratik/tcoffee/Version_11.00.8cbe486/bin:/home/pratik/tcoffee/Version_11.00.8cbe486/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/pratik/bioinfo/ugene-1.24.0:/home/pratik/meme/bin:/home/pratik/bioinfo/namd:/home/pratik/tcoffee/Version_11.00.8cbe486/bin/:/snap/bin:/usr/local/bin:/home/pratik/.local/bin
`

env | sort

`AMBERHOME=/home/pratik/bioinfo/amber16
CACHE_4_TCOFFEE=/home/pratik/.t_coffee/cache/
CLUTTER_IM_MODULE=xim
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=ubuntu
DIR_4_TCOFFEE=/home/pratik/tcoffee/Version_11.00.8cbe486
DISPLAY=:0
DYLD_LIBRARY_PATH=/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/rosetta:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/rosetta:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/rosetta
EMAIL_4_TCOFFEE=pratik.narain@gmail.com
GDMSESSION=ubuntu
GJS_DEBUG_OUTPUT=stderr
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_SHELL_SESSION_MODE=ubuntu
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/e347660d_7291_4ad6_b483_5a69cf932f77
GNOME_TERMINAL_SERVICE=:1.89
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
HOME=/home/pratik
IM_CONFIG_PHASE=2
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LD_LIBRARY_PATH=/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/rosetta:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/rosetta:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/rosetta:/opt/modeller9.17/lib/x86_64-intel8:/home/pratik/bioinfo/namd:/usr/lib32:/home/pratik/bioinfo/namd:
LOCKDIR_4_TCOFFEE=/home/pratik/tcoffee/Version_11.00.8cbe486/lck/
LOGNAME=pratik
MAFFT_BINARIES=/home/pratik/tcoffee/Version_11.00.8cbe486/plugins/linux/
MANPATH=:/home/pratik/bioinfo/ugene-1.24.0
MINTDIR=/home/pratik/bioinfo/MintV32
OLDPWD=/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104
PAPERSIZE=letter
PATH=/home/pratik/tcoffee/Version_11.00.8cbe486/bin:/home/pratik/tcoffee/Version_11.00.8cbe486/bin:/home/pratik/tcoffee/Version_11.00.8cbe486/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/pratik/bioinfo/ugene-1.24.0:/home/pratik/meme/bin:/home/pratik/bioinfo/namd:/home/pratik/tcoffee/Version_11.00.8cbe486/bin/:/snap/bin:/usr/local/bin:/home/pratik/.local/bin
PERL5LIB=:/home/pratik/tcoffee/Version_11.00.8cbe486/perl/lib/perl5
PWD=/home/pratik
PYROSETTA_DATABASE=/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104/database
PYROSETTA=/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104
PYTHONPATH=/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104:/home/pratik/bioinfo/PyRosetta.monolith.ubuntu.release-104::/opt/modeller9.17/modlib:/opt/modeller9.17/lib/x86_64-intel8:/opt/modeller9.17/lib/x86_64-intel8/python2.5:/opt/modeller9.17/lib/x86_64-intel8/python3.0:/opt/modeller9.17/lib/x86_64-intel8/python3.2:/opt/modeller9.17/lib/x86_64-intel8/python3.3
QT4_IM_MODULE=xim
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
SCHRODINGER=/opt/schrodinger2016-2/
SESSION_MANAGER=local/pratik-desktop:@/tmp/.ICE-unix/879,unix/pratik-desktop:/tmp/.ICE-unix/879
SHELL=/bin/bash
SHLVL=1
SSH_AGENT_PID=1052
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
TEXTDOMAINDIR=/usr/share/locale/
TEXTDOMAIN=im-config
TMP_4_TCOFFEE=/home/pratik/tcoffee/Version_11.00.8cbe486/tmp/
USERNAME=pratik
USER=pratik
_=/usr/bin/env
VMDNOOPTIX=1
VTE_VERSION=5202
WINDOWPATH=1
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_ID=1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
XMODIFIERS=@im=ibus`

**Comment by jaimergp** [comment] 2018-09-27 14:13
Hint: `$PYTHONPATH` might affect the installation. Please try to `unset` it first.

**Comment by pratik-narain** [comment] 2018-09-27 14:35
PATH
`/home/pratik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`
env | sort

`CLUTTER_IM_MODULE=xim
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=ubuntu
DISPLAY=:0
GDMSESSION=ubuntu
GJS_DEBUG_OUTPUT=stderr
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_SHELL_SESSION_MODE=ubuntu
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/6c360d95_5973_44ae_aaf2_eacea69b8829
GNOME_TERMINAL_SERVICE=:1.100
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
HOME=/home/pratik
IM_CONFIG_PHASE=2
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=pratik
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PAPERSIZE=letter
PATH=~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/pratik/bioinfo
QT4_IM_MODULE=xim
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
SESSION_MANAGER=local/pratik-desktop:@/tmp/.ICE-unix/892,unix/pratik-desktop:/tmp/.ICE-unix/892
SHELL=/bin/bash
SHLVL=1
SSH_AGENT_PID=985
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
TEXTDOMAINDIR=/usr/share/locale/
TEXTDOMAIN=im-config
USERNAME=pratik
USER=pratik
_=/usr/bin/env
VTE_VERSION=5202
WINDOWPATH=1
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_ID=1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
XMODIFIERS=@im=ibus`

So I got your hint and cleaned up my environment variables as you can see in the env | sort output. Still getting the same error.

**Comment by jaimergp** [comment] 2018-09-27 14:42
The variables look OK, so I don't have any more suggestions... :/ If you want, we can arrange a one-on-one remote session so I can further debug it personally, but I understand that it might be not adequate depending on your IT policies. Reach me by email if you are interested: jaime.rodriguezguerra@uab.cat

**Comment by pratik-narain** [comment] 2018-09-27 16:07
Well. Can you do anydesk? Or teamviewer?

**Comment by jaimergp** [comment] 2018-09-27 16:08
TeamViewer is perfect.

**Comment by jaimergp** [comment] 2019-02-08 16:39
I'll close this since all my tests have been successful for Ubuntu 18.04 and no contact was ever established. Feel free to reopen if needed.

**Closed as completed by jaimergp** 2019-02-08 16:39 UTC
